"""
fetch_data.py  —  CEDEAR Dashboard
Descarga datos diarios (3 años) de Yahoo Finance para todos los CEDEARs
negociables en BYMA que cotizan en NYSE / NASDAQ.
Calcula: RSI(14), MACD(12/26/9), MA20/50/200, Bandas de Bollinger(20,2),
ADX, Stochastic, ROC, OBV, cruces de medias y divergencias.
Genera: data/market_data.json
"""

import json
import os
import time
import pandas as pd
from datetime import datetime, timedelta
import yfinance as yf

# ── Universo CEDEAR — NYSE / NASDAQ únicamente ────────────────────────────────
# (se mantiene igual que el original)

CEDEARS = {
    # Tecnología
    "AAPL":  {"name": "Apple",                     "sector": "tech"},
    "MSFT":  {"name": "Microsoft",                 "sector": "tech"},
    "GOOGL": {"name": "Alphabet",                  "sector": "tech"},
    "AMZN":  {"name": "Amazon",                    "sector": "tech"},
    "TSLA":  {"name": "Tesla",                     "sector": "tech"},
    "META":  {"name": "Meta Platforms",            "sector": "tech"},
    "NVDA":  {"name": "NVIDIA",                    "sector": "tech"},
    "NFLX":  {"name": "Netflix",                   "sector": "tech"},
    "ORCL":  {"name": "Oracle",                    "sector": "tech"},
    "CRM":   {"name": "Salesforce",                "sector": "tech"},
    "INTC":  {"name": "Intel",                     "sector": "tech"},
    "AMD":   {"name": "AMD",                       "sector": "tech"},
    "QCOM":  {"name": "Qualcomm",                  "sector": "tech"},
    "ADBE":  {"name": "Adobe",                     "sector": "tech"},
    "PYPL":  {"name": "PayPal",                    "sector": "tech"},
    "UBER":  {"name": "Uber",                      "sector": "tech"},
    "SPOT":  {"name": "Spotify",                   "sector": "tech"},
    "SHOP":  {"name": "Shopify",                   "sector": "tech"},
    "CSCO":  {"name": "Cisco",                     "sector": "tech"},
    "IBM":   {"name": "IBM",                       "sector": "tech"},
    "AMAT":  {"name": "Applied Materials",         "sector": "tech"},
    "ADI":   {"name": "Analog Devices",            "sector": "tech"},
    "LRCX":  {"name": "Lam Research",              "sector": "tech"},
    "MRVL":  {"name": "Marvell Technology",        "sector": "tech"},
    "MU":    {"name": "Micron Technology",         "sector": "tech"},
    "MSTR":  {"name": "MicroStrategy",             "sector": "tech"},
    "NOW":   {"name": "ServiceNow",                "sector": "tech"},
    "TEAM":  {"name": "Atlassian",                 "sector": "tech"},
    "DOCU":  {"name": "DocuSign",                  "sector": "tech"},
    "SNOW":  {"name": "Snowflake",                 "sector": "tech"},
    "PLTR":  {"name": "Palantir",                  "sector": "tech"},
    "PANW":  {"name": "Palo Alto Networks",        "sector": "tech"},
    "COIN":  {"name": "Coinbase",                  "sector": "tech"},
    "ARM":   {"name": "ARM Holdings",              "sector": "tech"},
    "ASML":  {"name": "ASML Holding",              "sector": "tech"},
    "TSM":   {"name": "Taiwan Semiconductor",      "sector": "tech"},
    "AVGO":  {"name": "Broadcom",                  "sector": "tech"},
    "TXN":   {"name": "Texas Instruments",         "sector": "tech"},
    "SWKS":  {"name": "Skyworks Solutions",        "sector": "tech"},
    "ISRG":  {"name": "Intuitive Surgical",        "sector": "tech"},
    "CRWV":  {"name": "CoreWeave",                 "sector": "tech"},
    "ALAB":  {"name": "Astera Labs",               "sector": "tech"},
    "ASTS":  {"name": "AST SpaceMobile",           "sector": "tech"},
    "RKLB":  {"name": "Rocket Lab",                "sector": "tech"},
    "OKLO":  {"name": "Oklo",                      "sector": "tech"},
    "RGTI":  {"name": "Rigetti Computing",         "sector": "tech"},
    "AI":    {"name": "C3.AI",                     "sector": "tech"},
    "PATH":  {"name": "UiPath",                    "sector": "tech"},
    "TWLO":  {"name": "Twilio",                    "sector": "tech"},
    "ZM":    {"name": "Zoom",                      "sector": "tech"},
    "SNAP":  {"name": "Snap",                      "sector": "tech"},
    "PINS":  {"name": "Pinterest",                 "sector": "tech"},
    "RBLX":  {"name": "Roblox",                    "sector": "tech"},
    "ROKU":  {"name": "Roku",                      "sector": "tech"},
    "ETSY":  {"name": "Etsy",                      "sector": "tech"},
    "EBAY":  {"name": "eBay",                      "sector": "tech"},
    "HOOD":  {"name": "Robinhood",                 "sector": "tech"},
    "INFY":  {"name": "Infosys",                   "sector": "tech"},
    "SAP":   {"name": "SAP SE",                    "sector": "tech"},
    "SONY":  {"name": "Sony",                      "sector": "tech"},
    "NTES":  {"name": "NetEase",                   "sector": "tech"},
    "TCOM":  {"name": "Trip.com",                  "sector": "tech"},
    "TEM":   {"name": "Tempus AI",                 "sector": "tech"},
    "GLOB":  {"name": "Globant",                   "sector": "tech"},
    "SATL":  {"name": "Satellogic",                "sector": "tech"},
    "GRMN":  {"name": "Garmin",                    "sector": "tech"},
    "ABNB":  {"name": "Airbnb",                    "sector": "tech"},
    "HPQ":   {"name": "HP Inc",                    "sector": "tech"},
    "ADP":   {"name": "ADP",                       "sector": "tech"},
    # Finanzas
    "JPM":   {"name": "JPMorgan Chase",            "sector": "finance"},
    "GS":    {"name": "Goldman Sachs",             "sector": "finance"},
    "BAC":   {"name": "Bank of America",           "sector": "finance"},
    "C":     {"name": "Citigroup",                 "sector": "finance"},
    "WFC":   {"name": "Wells Fargo",               "sector": "finance"},
    "MS":    {"name": "Morgan Stanley",            "sector": "finance"},
    "BLK":   {"name": "BlackRock",                 "sector": "finance"},
    "AXP":   {"name": "American Express",          "sector": "finance"},
    "V":     {"name": "Visa",                      "sector": "finance"},
    "MA":    {"name": "Mastercard",                "sector": "finance"},
    "SCHW":  {"name": "Charles Schwab",            "sector": "finance"},
    "BX":    {"name": "Blackstone",                "sector": "finance"},
    "BK":    {"name": "BNY Mellon",                "sector": "finance"},
    "USB":   {"name": "U.S. Bancorp",              "sector": "finance"},
    "AIG":   {"name": "AIG",                       "sector": "finance"},
    "SPGI":  {"name": "S&P Global",                "sector": "finance"},
    "MMC":   {"name": "Marsh & McLennan",          "sector": "finance"},
    "NU":    {"name": "Nu Holdings",               "sector": "finance"},
    "ITUB":  {"name": "Itaú Unibanco",             "sector": "finance"},
    "BBD":   {"name": "Banco Bradesco",            "sector": "finance"},
    "BSBR":  {"name": "Santander Brasil",          "sector": "finance"},
    "SAN":   {"name": "Banco Santander",           "sector": "finance"},
    "ING":   {"name": "ING Groep",                 "sector": "finance"},
    "HSBC":  {"name": "HSBC Holdings",             "sector": "finance"},
    "IBN":   {"name": "ICICI Bank",                "sector": "finance"},
    "HDB":   {"name": "HDFC Bank",                 "sector": "finance"},
    "KB":    {"name": "KB Financial",              "sector": "finance"},
    "PAGS":  {"name": "PagSeguro",                 "sector": "finance"},
    "XP":    {"name": "XP Inc",                    "sector": "finance"},
    # Energía
    "XOM":   {"name": "ExxonMobil",                "sector": "energy"},
    "CVX":   {"name": "Chevron",                   "sector": "energy"},
    "COP":   {"name": "ConocoPhillips",            "sector": "energy"},
    "SLB":   {"name": "Schlumberger",              "sector": "energy"},
    "BP":    {"name": "BP",                        "sector": "energy"},
    "HAL":   {"name": "Halliburton",               "sector": "energy"},
    "BKR":   {"name": "Baker Hughes",              "sector": "energy"},
    "OXY":   {"name": "Occidental Petroleum",      "sector": "energy"},
    "PSX":   {"name": "Phillips 66",               "sector": "energy"},
    "TTE":   {"name": "TotalEnergies",             "sector": "energy"},
    "EQNR":  {"name": "Equinor",                   "sector": "energy"},
    "PBR":   {"name": "Petrobras",                 "sector": "energy"},
    "VIST":  {"name": "Vista Energy",              "sector": "energy"},
    "VST":   {"name": "Vistra",                    "sector": "energy"},
    "CEG":   {"name": "Constellation Energy",      "sector": "energy"},
    "USO":   {"name": "US Oil Fund",               "sector": "energy"},
    # Consumo
    "WMT":   {"name": "Walmart",                   "sector": "consumer"},
    "KO":    {"name": "Coca-Cola",                 "sector": "consumer"},
    "PG":    {"name": "Procter & Gamble",          "sector": "consumer"},
    "MCD":   {"name": "McDonald's",                "sector": "consumer"},
    "NKE":   {"name": "Nike",                      "sector": "consumer"},
    "SBUX":  {"name": "Starbucks",                 "sector": "consumer"},
    "DIS":   {"name": "Disney",                    "sector": "consumer"},
    "COST":  {"name": "Costco",                    "sector": "consumer"},
    "TGT":   {"name": "Target",                    "sector": "consumer"},
    "HD":    {"name": "Home Depot",                "sector": "consumer"},
    "MDLZ":  {"name": "Mondelez",                  "sector": "consumer"},
    "PEP":   {"name": "PepsiCo",                   "sector": "consumer"},
    "PM":    {"name": "Philip Morris",             "sector": "consumer"},
    "MO":    {"name": "Altria",                    "sector": "consumer"},
    "CL":    {"name": "Colgate-Palmolive",         "sector": "consumer"},
    "KMB":   {"name": "Kimberly-Clark",            "sector": "consumer"},
    "HSY":   {"name": "Hershey",                   "sector": "consumer"},
    "LVS":   {"name": "Las Vegas Sands",           "sector": "consumer"},
    "CCL":   {"name": "Carnival",                  "sector": "consumer"},
    "BKNG":  {"name": "Booking Holdings",          "sector": "consumer"},
    "RACE":  {"name": "Ferrari",                   "sector": "consumer"},
    "TM":    {"name": "Toyota",                    "sector": "consumer"},
    "HMC":   {"name": "Honda",                     "sector": "consumer"},
    "GM":    {"name": "General Motors",            "sector": "consumer"},
    "F":     {"name": "Ford",                      "sector": "consumer"},
    "ROST":  {"name": "Ross Stores",               "sector": "consumer"},
    "TJX":   {"name": "TJX Companies",             "sector": "consumer"},
    "ARCO":  {"name": "Arcos Dorados",             "sector": "consumer"},
    "AMX":   {"name": "America Movil",             "sector": "consumer"},
    # Salud
    "JNJ":   {"name": "Johnson & Johnson",         "sector": "health"},
    "PFE":   {"name": "Pfizer",                    "sector": "health"},
    "MRK":   {"name": "Merck",                     "sector": "health"},
    "ABBV":  {"name": "AbbVie",                    "sector": "health"},
    "UNH":   {"name": "UnitedHealth",              "sector": "health"},
    "LLY":   {"name": "Eli Lilly",                 "sector": "health"},
    "AMGN":  {"name": "Amgen",                     "sector": "health"},
    "BIIB":  {"name": "Biogen",                    "sector": "health"},
    "GILD":  {"name": "Gilead Sciences",           "sector": "health"},
    "BMY":   {"name": "Bristol-Myers Squibb",      "sector": "health"},
    "MDT":   {"name": "Medtronic",                 "sector": "health"},
    "DHR":   {"name": "Danaher",                   "sector": "health"},
    "TMO":   {"name": "Thermo Fisher",             "sector": "health"},
    "ABT":   {"name": "Abbott Labs",               "sector": "health"},
    "AZN":   {"name": "AstraZeneca",               "sector": "health"},
    "GSK":   {"name": "GSK",                       "sector": "health"},
    "NVS":   {"name": "Novartis",                  "sector": "health"},
    "MRNA":  {"name": "Moderna",                   "sector": "health"},
    "VRTX":  {"name": "Vertex Pharmaceuticals",    "sector": "health"},
    "CVS":   {"name": "CVS Health",                "sector": "health"},
    "CAH":   {"name": "Cardinal Health",           "sector": "health"},
    # Industrial / Materiales
    "CAT":   {"name": "Caterpillar",               "sector": "industrial"},
    "BA":    {"name": "Boeing",                    "sector": "industrial"},
    "GE":    {"name": "GE Aerospace",              "sector": "industrial"},
    "MMM":   {"name": "3M",                        "sector": "industrial"},
    "HON":   {"name": "Honeywell",                 "sector": "industrial"},
    "RTX":   {"name": "Raytheon Technologies",     "sector": "industrial"},
    "LMT":   {"name": "Lockheed Martin",           "sector": "industrial"},
    "DE":    {"name": "Deere & Co.",               "sector": "industrial"},
    "UNP":   {"name": "Union Pacific",             "sector": "industrial"},
    "FDX":   {"name": "FedEx",                     "sector": "industrial"},
    "MSI":   {"name": "Motorola Solutions",        "sector": "industrial"},
    "JCI":   {"name": "Johnson Controls",          "sector": "industrial"},
    "DOW":   {"name": "Dow Inc",                   "sector": "industrial"},
    "DD":    {"name": "DuPont",                    "sector": "industrial"},
    "IP":    {"name": "International Paper",       "sector": "industrial"},
    "AVY":   {"name": "Avery Dennison",            "sector": "industrial"},
    "ECL":   {"name": "Ecolab",                    "sector": "industrial"},
    "GLW":   {"name": "Corning",                   "sector": "industrial"},
    "ACN":   {"name": "Accenture",                 "sector": "industrial"},
    "EFX":   {"name": "Equifax",                   "sector": "industrial"},
    "IFF":   {"name": "Intl Flavors",              "sector": "industrial"},
    "HOG":   {"name": "Harley-Davidson",           "sector": "industrial"},
    "DAL":   {"name": "Delta Air Lines",           "sector": "industrial"},
    "AAL":   {"name": "American Airlines",         "sector": "industrial"},
    "UAL":   {"name": "United Airlines",           "sector": "industrial"},
    "BNG":   {"name": "Bunge",                     "sector": "industrial"},
    # Minería / Metales
    "NEM":   {"name": "Newmont",                   "sector": "mining"},
    "AEM":   {"name": "Agnico Eagle",              "sector": "mining"},
    "KGC":   {"name": "Kinross Gold",              "sector": "mining"},
    "GFI":   {"name": "Gold Fields",               "sector": "mining"},
    "HMY":   {"name": "Harmony Gold",              "sector": "mining"},
    "PAAS":  {"name": "Pan American Silver",       "sector": "mining"},
    "FCX":   {"name": "Freeport-McMoRan",          "sector": "mining"},
    "BHP":   {"name": "BHP Group",                 "sector": "mining"},
    "RIO":   {"name": "Rio Tinto",                 "sector": "mining"},
    "VALE":  {"name": "Vale",                      "sector": "mining"},
    "SCCO":  {"name": "Southern Copper",           "sector": "mining"},
    "MUX":   {"name": "McEwen Mining",             "sector": "mining"},
    "HL":    {"name": "Hecla Mining",              "sector": "mining"},
    "CDE":   {"name": "Coeur Mining",              "sector": "mining"},
    "LAC":   {"name": "Lithium Americas",          "sector": "mining"},
    "NXE":   {"name": "NexGen Energy",             "sector": "mining"},
    # Brasil ADR
    "ABEV":  {"name": "Ambev",                     "sector": "brasil"},
    "ERJ":   {"name": "Embraer",                   "sector": "brasil"},
    "GGB":   {"name": "Gerdau",                    "sector": "brasil"},
    "SID":   {"name": "CSN",                       "sector": "brasil"},
    "BAK":   {"name": "Braskem",                   "sector": "brasil"},
    "BRFS":  {"name": "BRF SA",                    "sector": "brasil"},
    "SUZ":   {"name": "Suzano",                    "sector": "brasil"},
    "EBR":   {"name": "Eletrobras",                "sector": "brasil"},
    "SBS":   {"name": "Sabesp",                    "sector": "brasil"},
    "ELP":   {"name": "Copel",                     "sector": "brasil"},
    "UGP":   {"name": "Ultrapar",                  "sector": "brasil"},
    "STNE":  {"name": "StoneCo",                   "sector": "brasil"},
    "NTCO":  {"name": "Natura & Co",               "sector": "brasil"},
    "VIV":   {"name": "Telefônica Brasil",         "sector": "brasil"},
    "TIMB":  {"name": "TIM Brasil",                "sector": "brasil"},
    "MELI":  {"name": "MercadoLibre",              "sector": "brasil"},
    "ADGO":  {"name": "Adecoagro",                 "sector": "brasil"},
    # China ADR
    "BABA":  {"name": "Alibaba",                   "sector": "china"},
    "BIDU":  {"name": "Baidu",                     "sector": "china"},
    "JD":    {"name": "JD.com",                    "sector": "china"},
    "NIO":   {"name": "NIO",                       "sector": "china"},
    "PDD":   {"name": "PDD Holdings (Temu)",       "sector": "china"},
    "XPEV":  {"name": "XPeng",                     "sector":
